version: "3"

services:
  db:
    image: postgres
    volumes:
    - /home/entrant/project/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=prod
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
  db-test:
    image: postgres
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
  server:
    build: .
    restart: always
    ports:
    - 8000:8000
    volumes:
    - /home/entrant/project/:/code/
    depends_on:
      - db
    command: ./start.sh